package com.imcys.bilibilias.common.utils.download

import com.imcys.bilibilias.network.model.video.BILIVideoCCInfo
import java.text.DecimalFormat
import java.text.DecimalFormatSymbols
import java.util.Locale
import java.util.concurrent.TimeUnit

/**
 * CC字母在JSON格式时转换为
 */
object CCJsonToAss {

    /**
     * 构筑头部信息
     */
    fun buildHeadersInfo(
        title: String,
        playResX: String,
        playResY: String,
    ): String =
        """
        [Script Info]
        ; Script generated by BDT Danmaku Converter
        Title: $title
        ScriptType: v4.00+
        PlayResX:$playResX
        PlayResY:$playResY
        ScaledBorderAndShadow: no
        """.trimIndent()

    fun jsonToAss(
        videoCCInfo: BILIVideoCCInfo,
        title: String,
        playResX: String,
        playResY: String,
    ): String {
        // 组装头部信息
        val headersInfo = buildHeadersInfo(title, playResX, playResY)

        val fontStyleInfo = getFontStyleInfo()

        val ccInfo = buildCCInfo(videoCCInfo)

        // ⚠️ 不要再用多行 raw string + trimIndent 拼接（2026-09-15 复审 L7）：
        // 模板里 `$fontStyleInfo` / `$ccInfo` 前面带着源码缩进，而 `trimIndent()` 的最小缩进
        // 由首行（缩进 0）决定 → 结果里 `[V4+ Styles]` / `[Events]` 段头**带前导空格**，
        // 严格按行首匹配的解析器（ffmpeg 的 assdec 就是 `strncmp`）会直接忽略整段。
        return listOf(headersInfo, fontStyleInfo, ccInfo)
            .filter { it.isNotBlank() }
            .joinToString("\n")
    }

    fun getFontStyleInfo(): String {
        return """
        [V4+ Styles]
        Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        Style: Small,Microsoft YaHei,36,&H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0
        Style: Medium,Microsoft YaHei,52,&H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0
        Style: Large,Microsoft YaHei,64,&H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0
        Style: Larger,Microsoft YaHei,72,&H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0
        Style: ExtraLarge,Microsoft YaHei,90,&H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0
        """.trimIndent()
    }

    fun getFormat(): String {
        return """
        [Events]
        Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        """.trimIndent()
    }

    /**
     * 构建字幕体
     */
    private fun buildCCInfo(videoCCInfo: BILIVideoCCInfo): String {
        var danmakus = getFormat()
        videoCCInfo.body.forEach {
            val startTime = formatSeconds(it.from)
            // 6秒延迟
            val endTime = formatSeconds(it.to)

            danmakus += "Dialogue: 0,$startTime,$endTime,Large,,0000,0000,0000,,{\\pos(960,1050)\\c&H000000&}${it.content}\n"
        }

        return danmakus
    }

    /**
     * 时间格式化
     *
     * ⚠️ `DecimalFormat` 与 `String.format` 都必须绑 `Locale.ROOT`（2026-09-15 复审 A-M8）：
     * 默认 Locale 在 de/fr 等区域用逗号做小数点 → 生成 `0:00:01,50`，ASS 时间戳非法，
     * 而且逗号本身是 Dialogue 的字段分隔符，整行都会被切错。
     * 负数（接口给脏数据时）先夹回 0，避免出现 `0:00:-1.50`。
     */
    fun formatSeconds(seconds: Double): String {
        val safeSeconds = if (seconds.isNaN() || seconds < 0) 0.0 else seconds
        val formatter = DecimalFormat("00.00", DecimalFormatSymbols.getInstance(Locale.ROOT))
        val hours = TimeUnit.SECONDS.toHours(safeSeconds.toLong())
        val minutes = TimeUnit.SECONDS.toMinutes(safeSeconds.toLong()) % 60
        val remainingSeconds =
            safeSeconds - TimeUnit.HOURS.toSeconds(hours) - TimeUnit.MINUTES.toSeconds(minutes)
        return String.format(
            Locale.ROOT,
            "%d:%02d:%s",
            hours,
            minutes,
            formatter.format(remainingSeconds),
        )
    }
}